package name: com.kinshield
family 1:
    basic:
        subscription id: test.basic.1 # android only
        subscription name: Basic Plan 1 # android only
        plan:
            monthly:
                id: test.basic.monthly.1
                name: Basic Monthly 1
                price: 5.99
                android id: test-basic-monthly-1 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: test.basic.yearly.1
                name: Basic Yearly 1
                price: 59.99
                android id: test-basic-yearly-1 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    premium:
        subscription id: test.premium.1 # android only
        subscription name: Premium Plan 1 # android only
        plan:
            monthly:
                id: test.premium.monthly.1
                name: Premium Monthly 1
                price: 9.99
                android id: test-premium-monthly-1 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: test.premium.yearly.1
                name: Premium Yearly 1
                price: 99.99
                android id: test-premium-yearly-1 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
family 2:
    basic:
        subscription id: test.basic.2 # android only
        subscription name: Basic Plan 2 # android only
        plan:
            monthly:
                id: test.basic.monthly.2
                name: Basic Monthly 2
                price: 5.99
                android id: test-basic-monthly-2 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: test.basic.yearly.2
                name: Basic Yearly 2
                price: 59.99
                android id: test-basic-yearly-2 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    premium:
        subscription id: test.premium.2 # android only
        subscription name: Premium Plan 2 # android only
        plan:
            monthly:
                id: test.premium.monthly.2
                name: Premium Monthly 2
                price: 9.99
                android id: test-premium-monthly-2 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: test.premium.yearly.2
                name: Premium Yearly 2
                price: 99.99
                android id: test-premium-yearly-2 # android only
                android charge: immediately # android only | enum: immediately, at next billing date