package name: com.kinsense
family 51:
    care:
        subscription id: test.com.kinsense.family.care.51 # android only
        subscription name: Test Care Plan 51 # android only
        plan:
            monthly:
                id: com.kinsense.family.care.monthly.51
                name: Test Care Monthly 51
                price: 5.99
                android id: test-com-kinsense-family-care-monthly-51 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.care.yearly.51
                name: Test Care Yearly 51
                price: 59.99
                android id: test-com-kinsense-family-care-yearly-51 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    protect:
        subscription id: test.com.kinsense.family.protect.51 # android only
        subscription name: Test Protect Plan 51 # android only
        plan:
            monthly:
                id: com.kinsense.family.protect.monthly.51
                name: Test Protect Monthly 51
                price: 9.99
                android id: test-com-kinsense-family-protect-monthly-51 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.protect.yearly.51
                name: Test Protect Yearly 51
                price: 99.99
                android id: test-com-kinsense-family-protect-yearly-51 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
family 52:
    care:
        subscription id: test.com.kinsense.family.care.52 # android only
        subscription name: Test Care Plan 52 # android only
        plan:
            monthly:
                id: com.kinsense.family.care.monthly.52
                name: Test Care Monthly 52
                price: 5.99
                android id: test-com-kinsense-family-care-monthly-52 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.care.yearly.52
                name: Test Care Yearly 52
                price: 59.99
                android id: com-kinsense-family-care-yearly-52 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    protect:
        subscription id: test.com.kinsense.family.protect.52 # android only
        subscription name: Test Protect Plan 52 # android only
        plan:
            monthly:
                id: com.kinsense.family.protect.monthly.52
                name: Test Protect Monthly 52
                price: 9.99
                android id: test-com-kinsense-family-protect-monthly-52 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.protect.yearly.52
                name: Test Protect Yearly 52
                price: 99.99
                android id: com-kinsense-family-protect-yearly-52 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
family 53:
    care:
        subscription id: test.com.kinsense.family.care.53 # android only
        subscription name: Test Care Plan 53 # android only
        plan:
            monthly:
                id: com.kinsense.family.care.monthly.53
                name: Test Care Monthly 53
                price: 5.99
                android id: test-com-kinsense-family-care-monthly-53 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.care.yearly.53
                name: Test Care Yearly 53
                price: 59.99
                android id: test-com-kinsense-family-care-yearly-53 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    protect:
        subscription id: test.com.kinsense.family.protect.53 # android only
        subscription name: Test Protect Plan 53 # android only
        plan:
            monthly:
                id: com.kinsense.family.protect.monthly.53
                name: Test Protect Monthly 53
                price: 9.99
                android id: test-com-kinsense-family-protect-monthly-53 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.protect.yearly.53
                name: Test Protect Yearly 53
                price: 99.99
                android id: test-com-kinsense-family-protect-yearly-53 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
family 54:
    care:
        subscription id: test.com.kinsense.family.care.54 # android only
        subscription name: Test Care Plan 54 # android only
        plan:
            monthly:
                id: com.kinsense.family.care.monthly.54
                name: Test Care Monthly 54
                price: 5.99
                android id: test-com-kinsense-family-care-monthly-54 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.care.yearly.54
                name: Test Care Yearly 54
                price: 59.99
                android id: test-com-kinsense-family-care-yearly-54 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
    protect:
        subscription id: test.com.kinsense.family.protect.54 # android only
        subscription name: Test Protect Plan 54 # android only
        plan:
            monthly:
                id: com.kinsense.family.protect.monthly.54
                name: Test Protect Monthly 54
                price: 9.99
                android id: test-com-kinsense-family-protect-monthly-54 # android only
                android charge: immediately # android only | enum: immediately, at next billing date
            yearly:
                id: com.kinsense.family.protect.yearly.54
                name: Test Protect Yearly 54
                price: 99.99
                android id: test-com-kinsense-family-protect-yearly-54 # android only
                android charge: immediately # android only | enum: immediately, at next billing date