project_id: 129791107526
params:
    playstore_link:
        deleted: false
        data_type: string
        value: "market://details?id=com.kinshield"
    appstore_link:
        deleted: false
        data_type: string
        value: "https://itunes.apple.com/app/id6738410298?action=write-review"
    notif_token_update:
        deleted: false
        data_type: number
        value: 604800
    notif_permission_max:
        deleted: false
        data_type: number
        value: 3
    notif_permission_interval:
        deleted: false
        data_type: number
        value: 604800
    companion_qr_image:
        deleted: false
        data_type: string
        value: "https://content.getkinshield.com/app/qr-invitation.jpg"
    app_share_url:
        deleted: false
        data_type: string
        value: "https://app.getkinshield.com/"
    todo_priority:
        deleted: false
        data_type: json
        value: "{}"
    todo_priority_high:
        deleted: false
        data_type: number
        value: 10
    settings_faq_url:
        deleted: false
        data_type: string
        value: "https://getkinshield.com/?utm_source=inapp#faq"
    settings_about_url:
        deleted: false
        data_type: string
        value: "https://getkinshield.com/?utm_source=inapp"
    settings_privacy_url:
        deleted: false
        data_type: string
        value: "https://getkinshield.com/privacy-policy?utm_source=inapp"
    settings_tos_url:
        deleted: false
        data_type: string
        value: "https://getkinshield.com/tos?utm_source=inapp"
    settings_legal_info:
        deleted: true
        data_type: string
        value: "@ 2026 Uney GmbH. All rights are reserved."
    timeout_domain_check:
        deleted: false
        data_type: number
        value: 5
    store_link:
        deleted: true
        data_type: string
        value: "https://app.getkinshield.com"
    floating_button_hide_duration:
        deleted: false
        data_type: number
        value: 3600