project_id: 982086918463
params:
    playstore_link:
        description: "Android app store link"
        deleted: false
        data_type: string
        value: market://details?id=com.kinshield
    appstore_link:
        description: "iOS app store link"
        deleted: false
        data_type: string
        value: https://itunes.apple.com/app/id6738410298?action=write-review
    notif_token_update:
        description: "Second"
        deleted: false
        data_type: number
        value: 604800
    notif_permission_max:
        description: "Max number of notification permission dialog prompts"
        deleted: false
        data_type: number
        value: 3
    notif_permission_interval:
        description: "Second"
        deleted: false
        data_type: number
        value: 180
    companion_qr_image:
        description: ""
        deleted: false
        data_type: string
        value: https://content.getkinshield.com/app/qr-invitation.jpg
    app_share_url:
        description: ""
        deleted: false
        data_type: string
        value: https://app.getkinshield.com/
    todo_priority:
        description: ""
        deleted: false
        data_type: json
        value: '{}'
    todo_priority_high:
        description: ""
        deleted: false
        data_type: number
        value: 10
    settings_faq_url:
        description: ""
        deleted: false
        data_type: string
        value: https://getkinshield.com/?utm_source=inapp#faq
    settings_about_url:
        description: ""
        deleted: false
        data_type: string
        value: https://getkinshield.com/?utm_source=inapp
    settings_privacy_url:
        description: ""
        deleted: false
        data_type: string
        value: https://getkinshield.com/privacy-policy?utm_source=inapp
    settings_tos_url:
        description: ""
        deleted: false
        data_type: string
        value: https://getkinshield.com/tos?utm_source=inapp
    settings_legal_info:
        description: ""
        deleted: true
        data_type: string
        value: '@ 2026 Uney GmbH. All rights are reserved.'
    timeout_domain_check:
        description: "Second"
        deleted: false
        data_type: number
        value: 5
    store_link:
        description: "Alternate link to app store for iOS and android, in case app store not defined"
        deleted: true
        data_type: string
        value: https://app.getkinshield.com
    floating_button_hide_duration:
        description: ""
        deleted: false
        data_type: number
        value: 3600
    settings_message_app:
        description: "Show or hide the message app feature"
        deleted: false
        data_type: boolean
        value: true
    paywall_onboarding:
        description: ""
        deleted: false
        data_type: boolean
        value: true
    android_payment:
        description: ""
        deleted: true
        data_type: boolean
        value: false
    alerts_paywall_reminder_threshold_days:
        description: "Day"
        deleted: true
        data_type: number
        value: 7
    android_language_identification_threshold:
        description: ""
        deleted: false
        data_type: number
        value: 0.9
    full_alert_access_days:
        description: "Day"
        deleted: false
        data_type: number
        value: 30
    input_lang_threshold:
        description: The threshold to decide whether an input text mapped to a language.
        deleted: false
        data_type: number
        value: 0.9
    safari_extension_setup_url:
        description: ""
        deleted: false
        data_type: string
        value: https://safari-extension-setup-208492520960.us-west1.run.app
    input_lang_threshold_high:
        description: The upper confidence boundary for determining the input text language.
        deleted: false
        data_type: number
        value: 0.6
    input_lang_threshold_low:
        description: The lower confidence boundary for determining the input text language.
        deleted: false
        data_type: number
        value: 0.1
