package name: com.kinsense
group 10:
    level 1:
        id: com.kinsense.family.protect.annual.10
        name: KinSense Protect Yearly 10
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.10
        name: KinSense Protect Monthly 10
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.10
        name: KinSense Care Yearly 10
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.10
        name: KinSense Care Monthly 10
        price: 5.99
group 11:
    level 1:
        id: com.kinsense.family.protect.annual.11
        name: KinSense Protect Yearly 11
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.11
        name: KinSense Protect Monthly 11
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.11
        name: KinSense Care Yearly 11
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.11
        name: KinSense Care Monthly 11
        price: 5.99
group 12:
    level 1:
        id: com.kinsense.family.protect.annual.12
        name: KinSense Protect Yearly 12
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.12
        name: KinSense Protect Monthly 12
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.12
        name: KinSense Care Yearly 12
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.12
        name: KinSense Care Monthly 12
        price: 5.99
group 13:
    level 1:
        id: com.kinsense.family.protect.annual.13
        name: KinSense Protect Yearly 13
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.13
        name: KinSense Protect Monthly 13
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.13
        name: KinSense Care Yearly 13
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.13
        name: KinSense Care Monthly 13
        price: 5.99
group 14:
    level 1:
        id: com.kinsense.family.protect.annual.14
        name: KinSense Protect Yearly 14
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.14
        name: KinSense Protect Monthly 14
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.14
        name: KinSense Care Yearly 14
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.14
        name: KinSense Care Monthly 14
        price: 5.99
group 15:
    level 1:
        id: com.kinsense.family.protect.annual.15
        name: KinSense Protect Yearly 15
        price: 99.99
    level 2:
        id: com.kinsense.family.protect.monthly.15
        name: KinSense Protect Monthly 15
        price: 9.99
    level 3:
        id: com.kinsense.family.care.annual.15
        name: KinSense Care Yearly 15
        price: 59.99
    level 4:
        id: com.kinsense.family.care.monthly.15
        name: KinSense Care Monthly 15
        price: 5.99